### ISSUE TITLE
PHP 5.6.4

### ISSUE THREAD

**Issue by jbrooksuk** [Scalingo/appsdeck-buildpack-php#10]
How would I make this run PHP 5.6.4?

**Comment by Soulou** [comment]
I'll add the support for PHP 5.6.4 today

**Comment by jbrooksuk** [comment]
Brill!

**Comment by Soulou** [comment]
Hey @jbrooksuk 

http://changelog.appsdeck.eu/

5.6.4 is available! However I can't ensure that it's correctly working on other PaaS than https://appsdeck.eu, give it a try!
