### ISSUE TITLE
Procfile

### ISSUE THREAD

**Issue by jbrooksuk** [Scalingo/appsdeck-buildpack-php#11]
Do you guys not support Procfiles?

**Comment by Soulou** [comment]
Of course, your Procfile will work on our platform.

Here is the documentation: http://doc.appsdeck.eu/internals/procfile.html

Give it a try :-)

**Comment by jbrooksuk** [comment]
Say I'm using this buildpack on Heroku though, with Laravel and nginx?

**Comment by Soulou** [comment]
Actually, we are looking for a perfect compatibility. So if it's working on Heroku, it will work on Scalingo (note: Appsdeck is the old name, we are currently in name transition)

This buildpack is the one we are using by default, for a better frameworks compatibility (laravel, yii2 and others)

**Comment by jbrooksuk** [comment]
Ok cool, thanks!
