### ISSUE TITLE
Error with apcu

### ISSUE THREAD

**Issue by dubcanada** [Scalingo/appsdeck-buildpack-php#12]
Hello,

I am running Ubuntu 14.04 and I am using this buildpack but I am getting an error.

    -----> Bundling extensions
           apcu
    remote:
    remote: gzip: stdin: not in gzip format
    remote: tar: Child returned status 1
    remote: tar: Error is not recoverable: exiting now

Any idea of what is wrong? It seems to not like the apcu. If I look in the cache directory the file(s) it is only 70 kb's and it says

   <html><h1>Not Found</h1><p>The resource could not be found.</p></html>

Both phpredis and apcu seem to fail. mongo is fine.

I can manually fix it by going into the cache directory and wget'ing the file manually.

**Comment by Soulou** [comment]
Thank you for reporting the error, I'll fix that asap !

**Comment by Soulou** [comment]
```
-----> Bundling NGINX 1.6.2
-----> Bundling PHP 5.6.4
-----> Bundling extensions
       apcu
       phpredis
       mongo
-----> Setting up default configuration
-----> Vendoring binaries into slug
```

No problem with me.

Which PHP version are you using?

**Comment by dubcanada** [comment]
lol that was super fast. I am using `PHP 5.3.28` and a PHP (classic) app.

**Comment by Soulou** [comment]
```
-----> Use /tmp/b for build
-----> Bundling NGINX 1.6.2
       Checksums match. Fetching from cache.
-----> Bundling PHP 5.3.28
-----> Bundling extensions
       apcu

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
 !     An error occured during buildpack compilation
```

Ok I got it

**Comment by Soulou** [comment]
Ok it should work now, reopen if not ;-)
