### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by jbrooksuk** [Scalingo/appsdeck-buildpack-php#9]
Is it possible for me to use this buildpack for a PHP app, but during the `postdeploy` phase, get `gulp` to build assets?

**Comment by jbrooksuk** [comment]
@Soulou any advice?

**Comment by Soulou** [comment]
Hi @jbrooksuk, sorry for the delay

Yes you can run any command you wish after PHP/node installation, just define them in your compose.json in:

```json
{
  ...
  "extra": {
    "paas": {
      "compile": [
        "gulp bundle"
      ]
    }
  }
}

**Comment by jbrooksuk** [comment]
So I just add gulp to my dependencies and this will work?

**Comment by Soulou** [comment]
Yes that's it !

**Comment by jbrooksuk** [comment]
Ok, thanks!

**Comment by jbrooksuk** [comment]
What about bower? Can I install that as a dependency and add it to the `compile` array?

**Comment by Soulou** [comment]
Yes that's exactly the same

**Comment by jbrooksuk** [comment]
When it's building my app it says bower isn't a command. It's a dependency though.

**Comment by Soulou** [comment]
I'll take time to build an example to show you =)

**Comment by jbrooksuk** [comment]
Cheers!

**Comment by jbrooksuk** [comment]
For now, I've forked the buildpack and manually install it.

**Comment by Soulou** [comment]
Hi again @jbrooksuk 

* You can find a sample application using PHP Slim framework. It handles assets compilation with `bower` and `gulp` as you were asking: https://github.com/Scalingo/sample-php-nodejs
* The application is live here: http://sample-php-nodejs.scalingo.io
